// <auto-generated />
#nullable enable
using System;
using System.Resources;
using System.Globalization;

namespace ExpenseTracker.Resources
{
    /// <summary>
    /// Strongly-typed resource class for Strings.resx
    /// </summary>
    public class Strings
    {
        private static ResourceManager? resourceMan;
        private static CultureInfo? resourceCulture;

        public Strings() { }

        public static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan == null)
                {
                    // Resource file is in Resources/Strings/Strings.resx; the manifest name includes the folder.
                    resourceMan = new ResourceManager("ExpenseTracker.Resources.Strings.Strings", typeof(Strings).Assembly);
                }
                return resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => resourceCulture ?? CultureInfo.CurrentUICulture;
            set => resourceCulture = value;
        }

        public static string AppTitle => ResourceManager.GetString("AppTitle", Culture) ?? string.Empty;
        public static string WelcomeBack => ResourceManager.GetString("WelcomeBack", Culture) ?? string.Empty;
        public static string SignInPrompt => ResourceManager.GetString("SignInPrompt", Culture) ?? string.Empty;

        public static string EmailAddress => ResourceManager.GetString("EmailAddress", Culture) ?? string.Empty;
        public static string Password => ResourceManager.GetString("Password", Culture) ?? string.Empty;
        public static string SignIn => ResourceManager.GetString("SignIn", Culture) ?? string.Empty;
        public static string ForgotPassword => ResourceManager.GetString("ForgotPassword", Culture) ?? string.Empty;

        public static string CreateAccount => ResourceManager.GetString("CreateAccount", Culture) ?? string.Empty;
        public static string JoinUs => ResourceManager.GetString("JoinUs", Culture) ?? string.Empty;

        public static string ResetPassword => ResourceManager.GetString("ResetPassword", Culture) ?? string.Empty;
        public static string ResetInstruction => ResourceManager.GetString("ResetInstruction", Culture) ?? string.Empty;

         public static string ChangePassword => ResourceManager.GetString("ChangePassword", Culture) ?? string.Empty;
        public static string SendResetLink => ResourceManager.GetString("SendResetLink", Culture) ?? string.Empty;

        public static string PlaceholderEmail => ResourceManager.GetString("PlaceholderEmail", Culture) ?? string.Empty;
        public static string PlaceholderPassword => ResourceManager.GetString("PlaceholderPassword", Culture) ?? string.Empty;
        public static string OrLabel => ResourceManager.GetString("OrLabel", Culture) ?? string.Empty;
        public static string NoAccountPrompt => ResourceManager.GetString("NoAccountPrompt", Culture) ?? string.Empty;
        public static string SignUp => ResourceManager.GetString("SignUp", Culture) ?? string.Empty;
        public static string FullName => ResourceManager.GetString("FullName", Culture) ?? string.Empty;
        public static string PlaceholderFullName => ResourceManager.GetString("PlaceholderFullName", Culture) ?? string.Empty;
        public static string PlaceholderCreatePassword => ResourceManager.GetString("PlaceholderCreatePassword", Culture) ?? string.Empty;
        public static string PlaceholderConfirmPassword => ResourceManager.GetString("PlaceholderConfirmPassword", Culture) ?? string.Empty;
        public static string AlreadyHaveAccount => ResourceManager.GetString("AlreadyHaveAccount", Culture) ?? string.Empty;
        public static string RememberPassword => ResourceManager.GetString("RememberPassword", Culture) ?? string.Empty;

        public static string ErrorTitle => ResourceManager.GetString("ErrorTitle", Culture) ?? string.Empty;
        public static string SuccessTitle => ResourceManager.GetString("SuccessTitle", Culture) ?? string.Empty;
        public static string PleaseEnterEmailAndPassword => ResourceManager.GetString("PleaseEnterEmailAndPassword", Culture) ?? string.Empty;
        public static string PleaseEnterEmail => ResourceManager.GetString("PleaseEnterEmail", Culture) ?? string.Empty;
        public static string PleaseFillAllFields => ResourceManager.GetString("PleaseFillAllFields", Culture) ?? string.Empty;
        public static string PasswordsDoNotMatch => ResourceManager.GetString("PasswordsDoNotMatch", Culture) ?? string.Empty;
        public static string AccountCreated => ResourceManager.GetString("AccountCreated", Culture) ?? string.Empty;
        public static string ResetLinkSent => ResourceManager.GetString("ResetLinkSent", Culture) ?? string.Empty;

        // Navigation Routes
        public static string RouteLogin => ResourceManager.GetString("RouteLogin", Culture) ?? string.Empty;
        public static string RouteSignup => ResourceManager.GetString("RouteSignup", Culture) ?? string.Empty;
        public static string RouteForgotPassword => ResourceManager.GetString("RouteForgotPassword", Culture) ?? string.Empty;
        public static string RouteAddExpense => ResourceManager.GetString("RouteAddExpense", Culture) ?? string.Empty;
        public static string RouteViewAllExpenses => ResourceManager.GetString("RouteViewAllExpenses", Culture) ?? string.Empty;
        public static string RouteBack => ResourceManager.GetString("RouteBack", Culture) ?? string.Empty;

        // Alert Messages
        public static string ValidationError => ResourceManager.GetString("ValidationError", Culture) ?? string.Empty;
        public static string PleaseSelectCategory => ResourceManager.GetString("PleaseSelectCategory", Culture) ?? string.Empty;
        public static string PleaseEnterAmount => ResourceManager.GetString("PleaseEnterAmount", Culture) ?? string.Empty;
        public static string PleaseEnterValidAmount => ResourceManager.GetString("PleaseEnterValidAmount", Culture) ?? string.Empty;
        public static string UserNotFound => ResourceManager.GetString("UserNotFound", Culture) ?? string.Empty;
        public static string ExpenseSavedSuccess => ResourceManager.GetString("ExpenseSavedSuccess", Culture) ?? string.Empty;
        public static string FailedToLoadExpenses => ResourceManager.GetString("FailedToLoadExpenses", Culture) ?? string.Empty;
        public static string FailedToViewExpense => ResourceManager.GetString("FailedToViewExpense", Culture) ?? string.Empty;
        public static string FailedToSaveExpense => ResourceManager.GetString("FailedToSaveExpense", Culture) ?? string.Empty;
        public static string RegistrationFailed => ResourceManager.GetString("RegistrationFailed", Culture) ?? string.Empty;
        public static string FailedToSendResetLink => ResourceManager.GetString("FailedToSendResetLink", Culture) ?? string.Empty;
        public static string AnErrorOccurred => ResourceManager.GetString("AnErrorOccurred", Culture) ?? string.Empty;
        public static string LoginFailed => ResourceManager.GetString("LoginFailed", Culture) ?? string.Empty;
        public static string LogoutConfirm => ResourceManager.GetString("LogoutConfirm", Culture) ?? string.Empty;
        public static string LogoutFailed => ResourceManager.GetString("LogoutFailed", Culture) ?? string.Empty;
        public static string LogoutError => ResourceManager.GetString("LogoutError", Culture) ?? string.Empty;
        public static string ProfilePageComingSoon => ResourceManager.GetString("ProfilePageComingSoon", Culture) ?? string.Empty;
        public static string SettingsPageComingSoon => ResourceManager.GetString("SettingsPageComingSoon", Culture) ?? string.Empty;
        public static string HelpPageComingSoon => ResourceManager.GetString("HelpPageComingSoon", Culture) ?? string.Empty;
        public static string FailedToLoadProfile => ResourceManager.GetString("FailedToLoadProfile", Culture) ?? string.Empty;
        public static string NameAndEmailRequired => ResourceManager.GetString("NameAndEmailRequired", Culture) ?? string.Empty;
        public static string PleaseEnterValidEmail => ResourceManager.GetString("PleaseEnterValidEmail", Culture) ?? string.Empty;
        public static string ProfileUpdatedSuccess => ResourceManager.GetString("ProfileUpdatedSuccess", Culture) ?? string.Empty;
        public static string PasswordChangeComingSoon => ResourceManager.GetString("PasswordChangeComingSoon", Culture) ?? string.Empty;
        public static string DeleteAccountConfirm => ResourceManager.GetString("DeleteAccountConfirm", Culture) ?? string.Empty;
        public static string DeleteAccountMessage => ResourceManager.GetString("DeleteAccountMessage", Culture) ?? string.Empty;
        public static string AccountDeleted => ResourceManager.GetString("AccountDeleted", Culture) ?? string.Empty;
        public static string YesButton => ResourceManager.GetString("YesButton", Culture) ?? string.Empty;
        public static string NoButton => ResourceManager.GetString("NoButton", Culture) ?? string.Empty;
        public static string OKButton => ResourceManager.GetString("OKButton", Culture) ?? string.Empty;
        public static string LogoutTitle => ResourceManager.GetString("LogoutTitle", Culture) ?? string.Empty;
    }
}